export const HERO_COLUMN_HEADERS = {
  name: ["Name"],
  rarity: ["Rarity"],
  talentName: ["Talents", "Talent Name"],
  talentDescription: ["Talents", "Description"],
  protagonist: ["Factions", "index(Images!$A$2:$L$2, 1, 1)"],
  glory: ["Factions", "index(Images!$A$2:$L$2, 1, 2)"],
  origin: ["Factions", "index(Images!$A$2:$L$2, 1, 3)"],
  princess: ["Factions", "index(Images!$A$2:$L$2, 1, 4)"],
  empire: ["Factions", "index(Images!$A$2:$L$2, 1, 5)"],
  strategic: ["Factions", "index(Images!$A$2:$L$2, 1, 6)"],
  dark: ["Factions", "index(Images!$A$2:$L$2, 1, 7)"],
  meteor: ["Factions", "index(Images!$A$2:$L$2, 1, 8)"],
  legends: ["Factions", "index(Images!$A$2:$L$2, 1, 9)"],
  mythic: ["Factions", "index(Images!$A$2:$L$2, 1, 10)"],
  tensei: ["Factions", "index(Images!$A$2:$L$2, 1, 11)"],
  time: ["Factions", "index(Images!$A$2:$L$2, 1, 12)"],
  startingClassName: ["Starting Class"],
  startingClassSkill1: ["Starting Class", "Skill 1\n(Level 1)"],
  startingClassSkill2: ["Starting Class", "Skill 2\n(Level 12)"],
  leftClassStartingPosition: ["Left Tier 2 Class"],
  middleClassStartingPosition: ["Middle Tier 2 Class"],
  rightClassStartingPosition: ["Right Tier 2 Class"],
  soldierBonusHP: ["Max Soldier Bonuses (%)", "HP"],
  soldierBonusATK: ["Max Soldier Bonuses (%)", "ATK"],
  soldierBonusDEF: ["Max Soldier Bonuses (%)", "DEF"],
  soldierBonusMDEF: ["Max Soldier Bonuses (%)", "MDEF"],
  trainingGroundUnlocks: ["Training Ground Unlocks"],
  bond2ReqString: ["Bond Power Unlocks", "Bond 2\n(Intimacy Lv. 10)"],
  bond3ReqString: ["Bond Power Unlocks", "Bond 3\n(Intimacy Lv. 15)"],
  bond4ReqString: ["Bond Power Unlocks", "Bond 4\n(Intimacy Lv. 23)"],
  bond5ReqString: ["Bond Power Unlocks", "Bond 5\n(Intimacy Lv. 25)"],
  bond4ReqChar: ["Bond Power Unlocks", "Bond 4 Character"],
  bond5ReqChar: ["Bond Power Unlocks", "Bond 5 Character"],
  heartBondsLevel4String: [
    "Heart Bonds",
    "Level 4 Heart Bond Effect\n(Defensive)",
  ],
  heartBondsLevel7String: [
    "Heart Bonds",
    "Level 7 Heart Bond Effect\n(Offensive)",
  ],
  exclusiveEquipmentName: ["Exclusive Equipment", "Name"],
  exclusiveEquipmentType: ["Exclusive Equipment", "Item Type"],
  exclusiveEquipmentEffect: ["Exclusive Equipment", "Effect"],
  awakeningSkillName: ["Awakening Skill", "Name"],
  awakeningSkillType: ["Awakening Skill", "Type"],
  awakeningSkillCD: ["Awakening Skill", "CD"],
  awakeningSkillRange: ["Awakening Skill", "Range"],
  awakeningSkillSpan: ["Awakening Skill", "Span"],
  awakeningSkillEffect: ["Awakening Skill", "Effect"],
  skinCount: ["Skin Count"],
};

export const EQUIPMENT_COLUMN_HEADERS = {
  name: ["Name"],
  slot: ["Slot"],
  type: ["Type"],
  quality: ["Quality"],
  user1: ["User 1"],
  user2: ["User 2"],
  user3: ["User 3"],
  user4: ["User 4"],
  stat1: ["Level 50 Flat Stat 1"],
  stat2: ["Level 50 Flat Stat 2"],
  equipSkill: ["Equip Skill Lv50"],
};

export const SOLDIER_COLUMN_HEADERS = {
  name: ["Name"],
  tier: ["Tier"],
  type: ["Type"],
  range: ["Range"],
  move: ["Move"],
  effect: ["Skills (Training Max)"],
  baseHp: ["Base\nHP"],
  baseAtk: ["Base\nATK"],
  baseDef: ["Base\nDEF"],
  baseMdef: ["Base\nMDEF"],
};

export const TRAINING_HEADERS = {
  name: ["Soldier Type"],
  gold: ["Aniki Drops →"],
  bronzeBooks: ["Basic Materials"],
  silverBooks: ["Special Materials"],
  goldBooks: ["Rare Materials"],
  epicBooks: ["Epic Materials"],
};

export const ANIKI_DROP_HEADERS = {
  vitaminA: ["Vitamin A"],
  vitaminB: ["Vitamin B"],
  vitaminC: ["Vitamin C"],
  vitaminD: ["Vitamin D"],
  vitaminE: ["Vitamin E"],
  vitaminF: ["Vitamin F"],
  springRod: ["Spring Rod"],
  dumbbell: ["Dumbbell"],
  pushUpStand: ["Push-Up Stand"],
  elasticRope: ["Elastic Rope"],
  gripper: ["Gripper"],
  rings: ["Rings"],
  sandbag: ["Sandbag"],
  barbell: ["Barbell"],
  chestMachine: ["Chest Machine"],
  abRoller: ["Ab Roller"],
  balanceBall: ["Balance Ball"],
  yogaMat: ["Yoga Mat"],
  darkNecklace: ["Dark Necklace"],
  brownEssentialOil: ["Brown Essential Oil"],
  devoutGloves: ["Devout Gloves"],
  prettySpray: ["Pretty Spray"],
  burningStraps: ["Burning Straps"],
  crazyShorts: ["Crazy Shorts"],
};

export const PATCHES_HEADERS = {
  id: ["ID"],
  date: ["Date"],
  info: ["Info"],
  globalReleaseDate: ["Global Release Date"],
  patchType: ["Patch Type (major/minor)"],
  patchName: ["Patch Name"],
  newHero1: ["New Hero 1"],
  newHero2: ["New Hero 2"],
  newHero3: ["New Hero 3"],
  newHero4: ["New Hero 4"],
  banner1Type: ["Banner 1 Type (standard/destiny/equipment)"],
  banner1Item1: ["Banner 1 Item 1"],
  banner1Item2: ["Banner 1 Item 2"],
  banner1Item3: ["Banner 1 Item 3"],
  banner1Item4: ["Banner 1 Item 4"],
  banner2Type: ["Banner 1 Type (standard/destiny/equipment)"],
  banner2Item1: ["Banner 2 Item 1"],
  banner2Item2: ["Banner 2 Item 2"],
  banner2Item3: ["Banner 2 Item 3"],
  banner2Item4: ["Banner 2 Item 4"],
  awakeningSkill1: ["Awakening Skill 1"],
  awakeningSkill2: ["Awakening Skill 2"],
  awakeningSkill3: ["Awakening Skill 3"],
  awakeningSkill4: ["Awakening Skill 4"],
  exclusive1: ["Exclusive 1"],
  exclusive2: ["Exclusive 2"],
  exclusive3: ["Exclusive 3"],
};

export const FINAL_COL_KEY = "FINAL_COLUMN";

export const CLASS_UPGDARE_MATERIALS_COLUMN_HEADERS = [
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "AA",
  "AB",
  "AC",
  "AD",
  "AE",
  "AF",
  "AG",
  "AH",
  "AI",
  "AJ",
  "AK",
  "AL",
  "AM",
  "AN",
  "AO",
  "AP",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AV",
  "AW",
  "AX",
  "AY",
  "AZ",
  "BA",
  "BB",
  "BC",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BK",
  "BL",
  "BM",
  "BN",
  "BO",
  "BP",
  "BQ",
  "BR",
  "BS",
  "BT",
  "BU",
  "BV",
  "BW",
  "BX",
  "BY",
  "BZ",
  "CA",
  "CB",
  "CC",
  "CD",
  "CE",
  "CF",
  "CG",
  "CH",
  "CI",
  "CJ",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CP",
  "CQ",
  "CR",
  "CS",
  "CT",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "CZ",
  "DA",
  "DB",
  "DC",
  "DD",
  "DE",
  "DF",
  "DG",
  "DH",
  "DI",
  "DJ",
  "DK",
  "DL",
  "DM",
  "DN",
  "DO",
  "DP",
  "DQ",
];

export interface ColIdMap {
  [key: string]: string;
}

export type HERO_COLUMN_IDS = {
  [key in keyof typeof HERO_COLUMN_HEADERS]: string;
};

export type EQUIPMENT_COLUMN_IDS = {
  [key in keyof typeof EQUIPMENT_COLUMN_HEADERS]: string;
};

export type SOLDIER_COLUMN_IDS = {
  [key in keyof typeof SOLDIER_COLUMN_HEADERS]: string;
};

export type TRAINING_HEADERS_IDS = {
  [key in keyof typeof TRAINING_HEADERS]: string;
};

export type PATCHES_IDS = {
  [key in keyof typeof PATCHES_HEADERS]: string;
};

export type ANIKI_DROP_HEADERS_IDS = {
  [key in keyof typeof ANIKI_DROP_HEADERS]: string;
};
